### ISSUE TITLE
UPnP search works in the iOS simulator, but it doesn't work on a real iPhone

### ISSUE THREAD

**Issue by oldstone88** [Hillpro/upnp_client#5]
### Is your feature request related to a problem? Please describe it

UPnP search works in the iOS simulator, but it doesn't work on a real iPhone. I tried to enable all permissions, but it still didn't help.
My info.Plist
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Mimiplayer</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>mimiplayer</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>LSMinimumSystemVersion</key>
    <string>14.0</string>
	<key>NSAppleMusicUsageDescription</key>
    <string>We use access to the library to play files.</string>
	<key>NSMicrophoneUsageDescription</key>
    <string>We use the microphone to record sound.</string>
	<key>NSPhotoLibraryUsageDescription</key>
    <string>We use access to the photo library to save recordings.</string>
	<key>NSLocalNetworkUsageDescription</key>
    <string>This app uses the local network to search for UPnP devices.</string>
	<key>NSCalendarsUsageDescription</key>
    <string>We use access to your calendar to plan events and reminders.</string>
	<key>NSContactsUsageDescription</key>
    <string>We use access to your contacts to improve social features.</string>
	<key>NSMotionUsageDescription</key>
    <string>We use motion data to improve the app's functionality.</string>
	<key>NSSpeechRecognitionUsageDescription</key>
    <string>We use speech recognition to enable voice commands.</string>
	<key>NSSiriUsageDescription</key>
    <string>We use Siri to provide voice-activated features.</string>
	<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
    <string>We use your location to provide location-based services.</string>
	<key>NSLocationWhenInUseUsageDescription</key>
    <string>We use your location to provide location-based services while using the app.</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
    <string>We use Bluetooth to connect to nearby devices.</string>
	<key>NSBonjourServices</key>
	<array>
    	<string>_upnp._tcp</string>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
    	<key>NSAllowsArbitraryLoads</key>
    	<true/>
	</dict>

</dict>
</plist>
`

### Describe the solution you'd like

A real iPhone will search for UPnP devices.

### Teachability, documentation, adoption, migration strategy

It is desirable to have a full example of settings for iOS (Info.plist, Podfile) and Android (AndroidManifest.xml).

### What is the motivation / use case for changing the behavior?

Faster and more understandable work with the plugin

**Comment by Hillpro** [comment]
Hello Sergey,

Thanks for filling this issue. This package is mostly tested on Android and Windows devices, so I am currently not aware of that bug for iPhone. I knew that recent version of iOS was restricting access to multicast sockets, but I didn't research further.

I am gonna look for a potential fix in Apple documentation and will update the package documentation with necessary entries in the Info.plist file.

Could you please provide me with the iPhone and iOS version this bug is currently affecting.

**Comment by Hillpro** [comment]
From what I have find so far, iOS 14+ applications need the `com.apple.developer.networking.multicast` entitlement to send or receive IP multicast traffic.

Here are some articles:
https://stackoverflow.com/questions/78127374/send-udp-socket-multicast-address-in-network-framework-ios-17-version
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast

Could you try those and tell me if this is working in your case ?

**Comment by oldstone88** [comment]
Hello! Sorry for the long wait. Here is my experience:

1. Go to https://developer.apple.com/contact/request/networking-multicast and fill out the form for your app.
2. Wait 30 days for the acceptance email.
3. Go to https://developer.apple.com/account/resources/identifiers/list.
4. Choose the needed app.
5. Go to "Additional Capabilities".
6. Mark "Multicast Networking".
7. Go to your project in VS Code.
8. In the terminal, type "open ios/Runner.xcworkspace".
9. Choose "Runner" -> "Signing & Capabilities" -> "+ capability" and search for "Multicast Networking".
10. Build your project.

P.S. My Info.plist is connected above.

**Comment by Hillpro** [comment]
Hello Sergey,

Thank you so much for the feedback, I'm glad it is finally working for you on a real iPhone.

I will definitly take your answer and include those step in the README to let people know how to publish an app with this package on iOS. Btw I will soon improve this project to support the full scope of the UPnP protocol and include UPnP IGD protocol, so this package could become more useful.

About your Info.plist connected above, did it change at all since you added the "Multicast Networking" capability. I can't see the `<key>com.apple.developer.networking.multicast</key>`. If it did get modified, can you send the new file or update the one above please :)

Thanks again to contributing to this package

**Comment by Hillpro** [comment]
Btw I will soon improve this project to support to full scope of the UPnP protocol and include UPnP IGD protocol, so this package could become more useful. 

And if you want to become a contributor to the package, you could open a new PR to update the "Usage" section of the README to include the steps to use this package on iOS devices and I would be happy to accept it !
